### ISSUE TITLE
playerctl not detecting stmps

### ISSUE THREAD

**Issue by mstcl** [spezifisch/stmps#1] opened 2024-04-11 20:03 UTC
Hi there, thanks for continuing stmp, I appreciate it.

## Issue

I can't get mpris to work (launched with `mpris`) flag. Invoking `playerctl -l` doesn't return anything

The machine I'm on uses Arch Linux on 6.8.4.

## Debugging

In D-Spy (a dbus debugger) a `org.mpris.MediaPlayer2.Player` shows up, but I'm not really sure why playerctl doesn't see it.

## Solution?

I've poked around the code and after finding some similar tutorials I've managed to make it work with playerctl on my machine. I haven't tested on any other platform.

I'm going to make a draft pull request soon with the changes.

**Comment by alscaldas** [comment] 2024-07-03 15:53
Hey @mstcl 

I've been trying some navidrome clients and found this one. I noticed that there hasn't been any new development for the last 8 months and MPRIS support still isn't working.

Do you happen to know if your changes got merged to the main project?

**Comment by mstcl** [comment] 2024-07-06 07:01
> Hey @mstcl
> 
> I've been trying some navidrome clients and found this one. I noticed that there hasn't been any new development for the last 8 months and MPRIS support still isn't working.
> 
> Do you happen to know if your changes got merged to the main project?

No it hasn't, there are quite a few open PRs. That being said, it's not a massive project and you could just apply the patches yourself and compile it locally.

**Comment by spezifisch** [comment] 2024-07-30 19:20
@mstcl @alscaldas 
Does #2 fix your issues and can we close this?

I can't reproduce this problem neither on my Arch nor Debian system.

**Comment by mstcl** [comment] 2024-07-30 20:16
> @mstcl @alscaldas Does #2 fix your issues and can we close this?

Cheers for taking a look at #2.

Still working for me so let's close this.

**Closed** 2024-07-30 20:24 UTC
Labels: bug
